fixing bash script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -104,27 +104,27 @@ runs:
         [ "${FAIL_ON}" = "errors" ] && { \
         echo " Checking unresolved errors"; \
         echo "-----------------------------------------------------------------"; \
-        grep "Rule Violation Summary (0 errors" $A/ort/scan-report.html >/dev/null; \
+        grep "Rule Violation Summary (0 errors" ${{ github.workspace }}/ort/scan-report.html >/dev/null; \
         export FAILED_EXEC=$?; \
         if [ $FAILED_EXEC -eq 0 ]; \
         then \
           echo "0 unresolved errors"; \
-        else; \
+        else \
           echo "FAIL: report has unresolved errors"; \
           exit 1; \
         fi; \
-        } || echo "Do not fail on report unresolved errors"; 
+        } || echo "Do not fail on report unresolved errors";
         echo "-----------------------------------------------------------------";
 
         [ "${FAIL_ON}" = "warnings" ] && { \
         echo " Checking unresolved errors/warnings"; \
         echo "-----------------------------------------------------------------"; \
-        grep "Rule Violation Summary (0 errors, 0 warnings" $A/ort/scan-report.html >/dev/null; \
+        grep "Rule Violation Summary (0 errors, 0 warnings" ${{ github.workspace }}/ort/scan-report.html >/dev/null; \
         export FAILED_EXEC=$?; \
         if [ $FAILED_EXEC -eq 0 ]; \
         then \
           echo "0 unresolved errors/warnings"; \
-        else; \
+        else \
           echo "FAIL: report has unresolved errors/warnings"; \
           exit 1; \
         fi; \
@@ -134,18 +134,16 @@ runs:
         [ "${FAIL_ON}" = "hints" ] && { \
         echo " Checking unresolved errors/warnings/hints"; \
         echo "-----------------------------------------------------------------"; \
-        grep "Rule Violation Summary (0 errors, 0 warnings, 0 hints to resolve)" $A/ort/scan-report.html >/dev/null; \
-        export FAILED_EXEC=$?; \
-        if [ $FAILED_EXEC -eq 0 ]; \
+        grep "Rule Violation Summary (0 errors, 0 warnings, 0 hints to resolve)" ${{ github.workspace }}/ort/scan-report.html >/dev/null; \
+        if [ $? -eq 0 ]; \
         then \
           echo "0 unresolved errors/warnings/hints"; \
-        else; \
+        else \
           echo "FAIL: report has unresolved errors/warnings/hints"; \
           exit 1; \
         fi; \
         } || echo "Do not fail on report unresolved errors/warnings/hints"; 
         echo "-----------------------------------------------------------------";
-  
 
     - name: Create output results directory and ORT_DATA_DIR=/project/.ort/
       id: results-dir
