better curly braces

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -280,21 +280,21 @@ runs:
         [ "${FAIL_ON}" = "errors" ] && { \
         echo " Checking unresolved errors"; \
         echo "-----------------------------------------------------------------"; \
-        grep "Rule Violation Summary (0 errors" ${{ github.workspace }}/ort/scan-report.html >/dev/null && echo "0 unresolved errors" || echo "FAIL: report has unresolved error(s)" && exit 1; \
+        grep "Rule Violation Summary (0 errors" ${{ github.workspace }}/ort/scan-report.html >/dev/null && echo "0 unresolved errors" || { echo "FAIL: report has unresolved error(s)" && exit 1; }; \
         echo "-----------------------------------------------------------------"; \
         };
 
         [ "${FAIL_ON}" = "warnings" ] && { \
         echo " Checking unresolved errors/warnings"; \
         echo "-----------------------------------------------------------------"; \
-        grep "Rule Violation Summary (0 errors, 0 warnings" ${{ github.workspace }}/ort/scan-report.html >/dev/null && echo "0 unresolved errors/warnings" || echo "FAIL: report has unresolved errors/warnings" && exit 1; \
+        grep "Rule Violation Summary (0 errors, 0 warnings" ${{ github.workspace }}/ort/scan-report.html >/dev/null && echo "0 unresolved errors/warnings" || { echo "FAIL: report has unresolved errors/warnings" && exit 1; }; \
         echo "-----------------------------------------------------------------"; \
         };
         
         [ "${FAIL_ON}" = "hints" ] && { \
         echo " Checking unresolved errors/warnings/hints"; \
         echo "-----------------------------------------------------------------"; \
-        grep "Rule Violation Summary (0 errors, 0 warnings, 0 hints to resolve)" ${{ github.workspace }}/ort/scan-report.html >/dev/null && echo "0 unresolved errors/warnings/hints" || echo "FAIL: report has unresolved errors/warnings/hints" && exit 1; \
+        grep "Rule Violation Summary (0 errors, 0 warnings, 0 hints to resolve)" ${{ github.workspace }}/ort/scan-report.html >/dev/null && echo "0 unresolved errors/warnings/hints" ||  { echo "FAIL: report has unresolved errors/warnings/hints" && exit 1; }; \
         echo "-----------------------------------------------------------------"; \
         } || echo "Do not fail on report unresolved errors/warnings/hints"
         echo "-----------------------------------------------------------------"
